### ISSUE TITLE
[管理画面] 各モデル内のMonthly reportの選択ボックスの内容がobject表記になっている

### ISSUE THREAD

**Issue by tamata78** [hr-dash/hr-dash#102]
## 概要

管理モデルのデータ作成画面に表示されるMonthly reportの選択ボックスの内容が
数値でなく、object表記(#MonthlyReport:0x007f9b54b49230)になる。
## 対象モデル

Monthly Report Comment
Monthly Report Tag

**Comment by bakunyo** [comment]
<img width="465" alt="2016-05-13 1 21 46" src="https://cloud.githubusercontent.com/assets/2487437/15222095/1c7a29e6-18a9-11e6-85b9-c914982f232f.png">

<img width="375" alt="2016-05-13 1 22 00" src="https://cloud.githubusercontent.com/assets/2487437/15222110/23fb1f9a-18a9-11e6-9ff4-68e619837842.png">

**Comment by bakunyo** [comment]
直ってたのでClose
