### ISSUE TITLE
Markdownで書けるようにする

### ISSUE THREAD

**Issue by bakunyo** [hr-dash/hr-dash#107]
月報とかコメントとか、テキストエリアのフィールドは基本そうしたい

**Comment by yhsn** [comment]
実装ごとに微妙に違う方言があるのがイライラの元になったりするので、
機能を入れたテキストエリアの近くには「書き方はここを見て」のリンクがあるとベターですね。

**Comment by bakunyo** [comment]
ありがとうございます！それいいですね :+1: 
できれば一番メジャーなやつがいいけど…GitHub Flavored Markdown？
いい感じのプラグインが見つかるといいな…

**Comment by bakunyo** [comment]
[marked.js](https://github.com/chjj/marked)使ってGFMで書けるようにしました〜
https://github.com/hr-dash/hr-dash/pull/110

**Comment by yhsn** [comment]
:+1:
