### ISSUE TITLE
グループ一覧表示する際に遅くなる可能性がある通信が存在

### ISSUE THREAD

**Issue by tamata78** [hr-dash/hr-dash#130]
下記、２つのURLより発生する通信に時間がかかるよう。fontのダウンロード。
https://fonts.gstatic.com/s/ubuntu/v8/zvCUQcxqeoKhyOlbifSAaevvDin1pK8aKteLpeZ5c0A.woff2
https://fonts.googleapis.com/css?family=Ubuntu:400,700

ネットワークの通信状態に問題がなければ、問題とはならない。
表示が遅いなどの問題が発生した場合に、fontのダウンロードせずに、アプリ内に保持するなどで通信が発生しないように対応する。

**Comment by ta-chibana** [comment]
fontのダウンロードは遅くなる原因にはならなそうなのでclose
