### ISSUE TITLE
長い（？）URLを入力するとエラー

### ISSUE THREAD

**Issue by ta-chibana** [hr-dash/hr-dash#143]

**Comment by bakunyo** [comment]
## 現状

<img width="630" alt="2016-04-30 15 21 24" src="https://cloud.githubusercontent.com/assets/2487437/14934289/40b54406-0ee7-11e6-8819-487c6475d1b3.png">

そもそも対応不要な気がする

**Comment by bakunyo** [comment]
Googleの場合
<img width="654" alt="2016-04-30 15 21 59" src="https://cloud.githubusercontent.com/assets/2487437/14934336/9134d800-0ee8-11e6-8cde-0db22e394a22.png">

**Comment by bakunyo** [comment]
Yahooの場合
<img width="665" alt="2016-04-30 15 33 18" src="https://cloud.githubusercontent.com/assets/2487437/14934361/f04dadf8-0ee8-11e6-9559-96b4bd3f2d17.png">

2chのスレｗ

**Comment by bakunyo** [comment]
そもそもそんな長い文字列で検索しようとしてる時点で悪意があるか間違ってるんだから、Clientエラーとして返すこと自体には問題ない気がする

あとは、 https://github.com/hr-dash/hr-dash/issues/143#issuecomment-215941657 
はWebrickのエラーだからNginx + Unicornにした時にどういうエラーになるかだけ確認しておくか

**Comment by bakunyo** [comment]
## Nginx + Unicornで試した

<img width="557" alt="2016-04-30 15 46 09" src="https://cloud.githubusercontent.com/assets/2487437/14934436/d9c245ba-0eea-11e6-9964-fe642eba8173.png">

**Comment by bakunyo** [comment]
素晴らしい！しかもNginxの時点で返してくれてる

**Comment by bakunyo** [comment]
@hr-dash/owners ってわけで、対応不要そうです。レビューお願いします！

**Comment by bakunyo** [comment]
## Yahoo!の場合（修正版）

もっと長い文字列で検索してみた
<img width="1271" alt="2016-04-30 15 50 47" src="https://cloud.githubusercontent.com/assets/2487437/14934457/62878c52-0eeb-11e6-8ae5-2686ff02f441.png">

**Comment by ta-chibana** [comment]
確かに必要なさそう！
良いと思います！

![LGTM](http://lgtm.in/p/mzG8pBeNp)

**Comment by Nobuhiko-Kudo** [comment]
いいと思います！！

**Comment by bakunyo** [comment]
ありがとうございます！Closeしますね〜
