### ISSUE TITLE
月報登録ボタンの位置をわかりやすい位置にする

### ISSUE THREAD

**Issue by ta-chibana** [hr-dash/hr-dash#146]
- headerとかに登録ボタン置いておく？
- 月報登録画面でいつの月報かを選択できるようにする #169
- 年も選択できるように（入社年月日から？）#169

**Comment by bakunyo** [comment]
月報メニューの一番下に月報登録リンクを追加する
- 登録済の場合はリンクをdisable（文字のみ）
- 月末5日間は当月、それ以降は先月（ロジックは実装済）

**Comment by bakunyo** [comment]
Merge完了
