### ISSUE TITLE
[月報登録] 月報のテンプレートを検討する

### ISSUE THREAD

**Issue by ta-chibana** [hr-dash/hr-dash#153]
- 判例？
- プレースホルダ的な項目を置いておく？

**Comment by bakunyo** [comment]
とりあえずplaceholderで検討

**Comment by bakunyo** [comment]
色々検討の余地はありそうだけど、とりあえずサンプル
@hr-dash/owners ご意見募集！

<img width="745" alt="2016-04-11 22 21 18" src="https://cloud.githubusercontent.com/assets/2487437/14428372/ceb30760-0033-11e6-8c5d-1dbce12bd970.png">
<img width="727" alt="2016-04-11 22 21 29" src="https://cloud.githubusercontent.com/assets/2487437/14428373/ceb4b466-0033-11e6-89f2-7c601ba1f426.png">
<img width="737" alt="2016-04-11 22 21 39" src="https://cloud.githubusercontent.com/assets/2487437/14428374/ceb5e656-0033-11e6-9eb0-2b45143d3533.png">

**Comment by bakunyo** [comment]
#### 今月の振り返り

```
例）
1. ・・・・のでできた。
2. ・・・・なのであまりできなかった。
3. ・・・・のでできなかった。
```

#### 来月の目標

```
例）
1. 
2. 
3.
```

**Comment by ta-chibana** [comment]
管理画面でプレースホルダーを登録できるようにする

**Comment by bakunyo** [comment]
参考：[RailsのDBの初期データ(rake db:seed用)をyamlで美しく管理する方法](http://qiita.com/yukimura1227/items/ff04eb6a771ffe1ab0b8)

**Comment by bakunyo** [comment]
おわった！！
