### ISSUE TITLE
[月報] show レイアウトが大きく崩れる

### ISSUE THREAD

**Issue by ta-chibana** [hr-dash/hr-dash#162]
- 月報登録後。showでレイアウトが崩れる。

**Comment by bakunyo** [comment]
事象確認
<img width="764" alt="2016-05-05 22 12 21" src="https://cloud.githubusercontent.com/assets/2487437/15044274/7d5f8ecc-130e-11e6-85c3-3428cf0fb2fd.png">

**Comment by bakunyo** [comment]
マージされたのでClose
