### ISSUE TITLE
[月報] コメントに大量の文字列を入力するとエラー

### ISSUE THREAD

**Issue by ta-chibana** [hr-dash/hr-dash#165]
- 要調査
- バリデーション？
- 他のところでもなるかも

**Comment by bakunyo** [comment]
文字数制限、何を基準にしたらいいか難しいけど
- http://office-taku.com/201209/web/2704.html
- http://d.hatena.ne.jp/longlow/20080915/p1

世に出てるサービス（コメント）を見てみると

| service | maxlength |
| :-- | :-- |
| Facebook | 2,666 |
| livedoor Blog | 800 |
| アメブロ | 2,000 |
| Yahoo!ブログ | 250 |

とりあえず3,000にしときますー

**Comment by bakunyo** [comment]
MergeされたのでClose
