### ISSUE TITLE
[月報] ページ数の値が大きいとエラー

### ISSUE THREAD

**Issue by ta-chibana** [hr-dash/hr-dash#166]
- kaminariに依存？

**Comment by Pujyoooo** [comment]
PG::NumericValueOutOfRange: ERROR:  bigint out of range
: SELECT  "monthly_reports".\* FROM "monthly_reports" LIMIT 10 OFFSET 92233720368547758060

bigint の最大値（9223372036854775807）をLIMITとOFFSETの値がオーバーしている為起きている

**Comment by bakunyo** [comment]
すまん、これ関連なので一緒に対応してもらっても良いかな？
↓この辺もエラーになる
http://localhost:3000/monthly_reports/users/3000000000000?target_year=3000
http://localhost:3000/monthly_reports/users/49?target_year=300000000000

正規表現使えるし、route.rbで制御するの良さそうな気がする！
http://qiita.com/kz_kazuki/items/23e43d1ec2607b96c070

**Comment by bakunyo** [comment]
MergeされたのでClose
