### ISSUE TITLE
Springの設定をする

### ISSUE THREAD

**Issue by bakunyo** [hr-dash/hr-dash#17]
このあたりを参考に。
http://ruby-rails.hatenadiary.com/entry/20141026/1414289421

**Comment by tamata78** [comment]
# springとは？
- コマンド実行を高速化する仕組み
- springサーバーが起動し、設定を監視。設定に応じたライブラリを事前に読み込んでくれる
- rails console/runner/generate/destroyとrakeタスクが高速化される
- 自動起動、終了されるので設定後は意識する必要なし

# springの使い方

rails, rake, rspec実行時に "bin/"を前につけて実行する。  
bin以下のrakeを呼ばないとspringが起動しないため  
- DBマイグレーションする
  $ bin/rake db:migrate
- テストを実行する
  $ bundle exec bin/rspec spec/test_spec.rb

# springの各種コマンド
- springサーバの状況確認
  $ bin/spring status
- springサーバを停止
  $ bin/spring stop
- spring自体を無効にする
  $ bin/spring binstub --remove --all

# 参考URL

http://ruby-rails.hatenadiary.com/entry/20141026/1414289421
http://qiita.com/bibio/items/58806063bd2365a9832a#4-3
http://qiita.com/jnchito/items/c5a0848144203dce6e26

**Comment by bakunyo** [comment]
https://github.com/hr-dash/hr-dash/pull/19
Merge済
