### ISSUE TITLE
[月報] textareaに大量の文字を入力するとエラー

### ISSUE THREAD

**Issue by ta-chibana** [hr-dash/hr-dash#171]

**Comment by bakunyo** [comment]
参考: [[月報] コメントに大量の文字列を入力するとエラー](https://github.com/hr-dash/hr-dash/issues/165)

この時参考にした記事だと、ブログ本文は　5,000〜20,000位がカバー範囲かなと思う。
月報の場合、各項目毎に分かれてるというのもありそんなに文字数要らないはず。
コメントは3,000にしたから、一旦5,000くらいで良いかな？

**Comment by bakunyo** [comment]
マージされたのでClose
