### ISSUE TITLE
[月報登録] 仕様した技術入力欄が異様にはみ出る

### ISSUE THREAD

**Issue by ta-chibana** [hr-dash/hr-dash#172]
- 画面が狭いとはみ出る？

**Comment by bakunyo** [comment]
#### 使用しているライブラリ

https://github.com/maxwells/bootstrap-tags

#### 自動幅調整

https://github.com/maxwells/bootstrap-tags/blob/f5195db836b919952719598f98066813bf3449e7/src/bootstrap-tags.coffee#L310
この辺りで`<input class="tags-input">`要素に幅がセットされる
この関数が呼ばれた時の幅で判定されるので、最初からウィンドウサイズが狭ければその幅に合わせてくれる。

#### 要点
- 月報入力画面表示後にウィンドウサイズを狭くしないかぎりははみ出ることが無い
- JSでinput要素の幅を指定（100%）することも可能だが、タグが追加／削除される毎にinput要素ごと差し替えられるので、都度幅指定しなければならない
- しかも、input要素が差し替えられた時には適切な幅でセットされる

input要素描画後にウィンドウサイズを狭めた時の対策にしかならないので、対応不要と思われる

@hr-dash/owners 問題なければCloseします。確認お願いします！

**Comment by bakunyo** [comment]
みんなの確認OK
Close
