### ISSUE TITLE
[管理画面] 良い感じにする

### ISSUE THREAD

**Issue by ta-chibana** [hr-dash/hr-dash#174]
- タスク洗い出し
- 第１回レビュー時に後回しにした分とか

**Comment by bakunyo** [comment]
やるかどうかは別として、レビュー会であがった管理画面系のIssue一覧
- 性別の入力チェックで何を入力していいかわからない
- 血液の入力チェックで何を入力していいかわからない
- 管理画面で自分のグループメンバーの編集、追加等を行いたい。
- 管理画面の一覧が崩れている（全部出ない）
- ADMIN / グループ / で、グループのコメントに大量データを入れるとエラー
- ADMIN / タグ / のリストで、ページングコンソールが変
- ADMIN / グループで、リーダーの名前？をクリックした画面に行くと、コメントの時間に0 translation missing: ja.active_admin.comments.deleteと出る。
- グループ作れない
- 作成時にDeleteDateはいらないのでは？
- DeleteDateの各項目の説明がない。月だけ日本語がついている
- Deleteしたグループのデータが検索条件のUSERSに出てくる

**Comment by bakunyo** [comment]
Group
- index
  - [x] destroyできないように
- show
  - [x] メンバー表示
- form
  - [x] deleted_atはdatepicker

**Comment by bakunyo** [comment]
- [x] グループ
- [x] タグ
- [x] ユーザー
- [x] プロフィール
- [x] ロール
- [x] 月報
- [x] 月報コメント
- [x] 月報タグ

Resourceごとに対応する

**Comment by bakunyo** [comment]
Tag
- index
  - [x] destroyできないように
- show
  - なし
- form
  - [x] 状態をSelectBoxに

**Comment by bakunyo** [comment]
User
- index
  - [x] destroyできないように
  - [x] グループはIDではなくグループ名（リンク付き）を表示
  - [x] created_at, updated_atは不要なので非表示
  - [x] グループの検索条件はid指定でなくグループを選択
- show
  - なし
- form
  - [x] 入社日、退社日はdatepickerで
  - [x] パスワードはここで変更させない

**Comment by bakunyo** [comment]
UserRole -> 特にやることなし

**Comment by bakunyo** [comment]
MonthlyReport
- index
  - [x] destroyできないように
  - [x] 業務内容、今月の振り返り、来月の目標、created_at, updated_atを非表示
  - [x] 対象年月は年月表示
  - [x] Userは名前とリンク表示
  - [x] Filterの修正
- show
  - [x] tagsを表示
  - [x] 担当工程を表示
- form
  - [x] ユーザーはselect box
  - [x] 対象月、公開日はdatepicker
  - [x] created_at, updated_atは非表示

**Comment by bakunyo** [comment]
MonthlyReportComment
- index
  - [x] ユーザーIDではなくリンク付きの名前に
  - [x] 月報はID（リンク付きに）
  - [x] updated_atを非表示
  - [x] filter, MonthlyReportをid指定
- show
  - なし
- form
  - [x] MonthlyReportをID指定に

**Comment by bakunyo** [comment]
MonthlyReportTag
- index
  - [x] 月報はID（リンク付きに）
  - [x] タグは名前（リンク付きに）
  - [x] created_at, updated_atを非表示
  - [x] filter, MonthlyReportをid指定
- show
  - なし
- form
  - [x] MonthlyReportをID指定に

**Comment by bakunyo** [comment]
残タスク（上記がすべてMergeされてから見直す）
- UserProfileの修正
- レビュー会であがった意見の再検討（https://github.com/hr-dash/hr-dash/issues/174#issuecomment-205263964）

**Comment by dodoichi** [comment]
#206 が終了したらcloseする。

**Comment by bakunyo** [comment]
あ、正確には、 #206 が終わった段階で再度管理画面（プロフィールの部分）いい感じにして終了の予定です 😃

**Comment by bakunyo** [comment]
MergeしたのでClose
