### ISSUE TITLE
パスワード変更できるようにする

### ISSUE THREAD

**Issue by ta-chibana** [hr-dash/hr-dash#176]

**Comment by t-tonchim** [comment]
ユーザー側で、パスワード忘れた時にリセットできる機能をつける

**Comment by bakunyo** [comment]
Rails Tutorial
http://railstutorial.jp/chapters/account_activation_password_reset?version=4.2#sec-password_reset

**Comment by bakunyo** [comment]
パスワード変更サンプル

## Twitter

#### 届いたメール

<img width="500" alt="2016-08-10 2 03 41" src="https://cloud.githubusercontent.com/assets/2487437/17525761/237e7d50-5e9f-11e6-832d-03e97ff9caf8.png">

#### リンク先

<img width="654" alt="2016-08-10 2 03 52" src="https://cloud.githubusercontent.com/assets/2487437/17525765/2d66f720-5e9f-11e6-8784-dfa6d0b26d25.png">

## Facebook

#### 届いたメール

<img width="619" alt="2016-08-10 2 05 07" src="https://cloud.githubusercontent.com/assets/2487437/17525770/38562458-5e9f-11e6-9cc1-f777030e08ce.png">

#### リンク先

<img width="572" alt="2016-08-10 2 05 25" src="https://cloud.githubusercontent.com/assets/2487437/17525774/3f314294-5e9f-11e6-94f2-b56849677a29.png">

**Comment by bakunyo** [comment]
Merge完了
