### ISSUE TITLE
血液型の値をwebconsoleで不正な値に変えた場合

### ISSUE THREAD

**Issue by bakunyo** [hr-dash/hr-dash#241]
ValidationErrorにならない

<img width="1059" alt="2016-05-27 1 48 13" src="https://cloud.githubusercontent.com/assets/2487437/15582699/459c1104-23ad-11e6-91dc-1ac37cb74cd6.png">

**Comment by ta-chibana** [comment]
#144 
これと同じでしょうか？
enumで定義されたプロパティに不正な値をsetする段階で例外出るので、enumに関しては直接リクエストパラメータを調べる必要があるのかなと思いましたが、もっと他に良い方法あるのでしょうか。

**Comment by bakunyo** [comment]
あー、ごめん、これと同じだわ！enumの件。
こっちはCloseしちゃうね〜 👍
