### ISSUE TITLE
ログインできない

### ISSUE THREAD

**Issue by t-tonchim** [hr-dash/hr-dash#251]
![2016-06-23 20 18 17](https://cloud.githubusercontent.com/assets/12590922/16301322/c0ca5e34-397f-11e6-877a-028d742b8b88.png)

フラッシュメッセージが一個だけだとeachできないからエラーになってるぽい

**Comment by bakunyo** [comment]
https://github.com/hr-dash/hr-dash/pull/252
こちらで解消済です
