### ISSUE TITLE
月報の対象月において、登録時に最新月を選択できないことがある。

### ISSUE THREAD

**Issue by Nobuhiko-Kudo** [hr-dash/hr-dash#262]
# 現象

以下の場合、最新月の月報を選択することができない。
- User#report_registrable_toの戻り値が月初(1日)になる場合
# 原因

User#report_registrable_months内において、以下の部分でDate型とTimeWithZone型で
比較してしまっているのが原因。

```
while month <= report_registrable_to
```

**Comment by bakunyo** [comment]
Merge完了
