### ISSUE TITLE
月報のタグ入力時にマウス使用時でバグ

### ISSUE THREAD

**Issue by Pujyoooo** [hr-dash/hr-dash#288]
月報登録時で使用した技術のタグを登録する時に
マウスタップでサジェストを選択すると
フォームに入力していた値とサジェストで選択した値両方がタグとして登録される

**Comment by bakunyo** [comment]
とりあえず原因となったPRは分かった。
https://github.com/hr-dash/hr-dash/pull/187

クリックするとタグ入力とフォーカスアウトが同時に起こるから、両方入ってしまう

**Comment by bakunyo** [comment]
`focusout` のタイミングで、そのイベントが
- suggestされたものをクリックしたことによるものなのか
- 単に別の場所をクリックしたりTabで次のフォームへ移動したのか

を区別するのは難しそう。
suggestされたものをクリックした時に、focusoutイベントを除去する　みたいなことはできるかもしれないけど、そこまでDOMに複雑なロジックを持たせたくない。

折衷案として、根本原因となったIssueの対処法を変えて、

```
focusoutのタイミングでタグ化されてない文字列は削除する
```

に変えたいと思う。

**Comment by Nobuhiko-Kudo** [comment]
🙆

**Comment by bakunyo** [comment]
Merge完了
