### ISSUE TITLE
タグ登録時に特定文字列で消せないタグとして登録される

### ISSUE THREAD

**Issue by Pujyoooo** [hr-dash/hr-dash#292]
月報タグ登録時に
- <>

をタグとして入力すると消しても消えないタグとして登録されてしまう

**Comment by Pujyoooo** [comment]
月報一覧で上記タグを登録されている月報でもタグとして表示されていない事がある

**Comment by bakunyo** [comment]
これ、ブラックリスト or ホワイトリスト作った方がいい気がしたけど、結構仕様決めるの面倒くさそうだ…

**Comment by bakunyo** [comment]
http://railsguides.jp/security.html#%E3%82%AF%E3%83%AD%E3%82%B9%E3%82%B5%E3%82%A4%E3%83%88%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%97%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0-xss-%E5%AF%BE%E5%BF%9C%E7%AD%96

> 特にXSSの場合、ブラックリストではなくホワイトリストに基づいた入力フィルタを実施することが絶対重要です。ホワイトリストフィルタでは特定の値のみが許可され、それ以外の値はすべて拒否されます。ブラックリストを元にしている限り、必ず将来漏れが生じます。

**Comment by bakunyo** [comment]
Merge完了
