### ISSUE TITLE
[月報登録] 登録済みの月報の編集で下書き保存を行うと予期しない表示になる

### ISSUE THREAD

**Issue by ta-chibana** [hr-dash/hr-dash#293]
## 手順・事象
1. 登録した月報を編集する
2. 更新時に「下書き保存」でセーブする
3. 詳細画面を確認
   - 編集した月報が、詳細画面にて「下書き中」となってしまう
   - 一覧では「登録済み」
## 改修案
- WIPは不要？

**Comment by bakunyo** [comment]
MergeしたのでClose
