### ISSUE TITLE
logに出力しない方がいいものをフィルターする

### ISSUE THREAD

**Issue by t-tonchim** [hr-dash/hr-dash#331]
デフォルトの設定だとパスワード変更時の確認用パスワードがログに出力されるはずなので
config/initializers/filter_parameter_logging.rbの記述を変更する。

参照
http://qiita.com/kakkunpakkun/items/4639bc653924e2dc8dbe

**Comment by bakunyo** [comment]
@tomoyuki-tanaka 既にfilter済だったのでCloseします
<img width="1272" alt="2016-10-03 15 41 49" src="https://cloud.githubusercontent.com/assets/2487437/19029314/184aa704-8980-11e6-96dc-e66d69b33b7c.png">
