### ISSUE TITLE
管理画面のDashboardを活用する

### ISSUE THREAD

**Issue by bakunyo** [hr-dash/hr-dash#345]
# 概要

管理画面のDashboardを活用する

まだ何も無い状態なので、運営的に気になる指標を表示したい。
たとえば、
- 最新の月報提出状況（グループ別）
- コメント数ランキング（直近3ヶ月、人別、月報別など）
- 未登録のタグ一覧

など
# 再現・確認手順（任意）
# ToDo
- [x] ラベル付け

**Comment by ta-chibana** [comment]
merged
