### ISSUE TITLE
月報のコメント数を表示する

### ISSUE THREAD

**Issue by bakunyo** [hr-dash/hr-dash#355]
# 概要
一覧で表示
counter_cache で良さそう

# 再現・確認手順（任意）

# ToDo

- [x] ラベル付け

**Comment by ta-chibana** [comment]
- [x] アップデート時、以下のRakeタスクを叩く

```
$ bundle exec rake comments_counter:calculate
```

**Comment by bakunyo** [comment]
Rakeタスク実行完了＆Merge済なのでClose
