### ISSUE TITLE
フレンドリーフォワーディングを実装する

### ISSUE THREAD

**Issue by t-tonchim** [hr-dash/hr-dash#372]
# 概要
ログイン時、ログイン前にアクセスしようとしていたページがあればリダイレクトしてくれるようにする。
レイチュー９章のやり方でできればいいけどDeviseがからむから、別の方法になるかもしれない

# 再現・確認手順（任意）

# ToDo

- [x] ラベル付け

**Comment by bakunyo** [comment]
MergeされたのでClose
