### ISSUE TITLE
[管理画面] 退職者の月報削除機能のテストを書く

### ISSUE THREAD

**Issue by ta-chibana** [hr-dash/hr-dash#377]
# 概要

`app/admin/user.rb` の `delete_monthly_report` あたりが対象。
退職したユーザーのすべての月報と、それらの月報に紐づくすべての情報を物理削除する。
追加するときにテストを書いていないので追加する。

## 確認事項

- 対象のユーザーのすべての月報が削除されること
- 退職者の月報しか削除できないこと
- 削除された月報に紐づく情報がすべて削除されること（以下が削除されるはず...）
  - 月報コメント
  - 月報のタグ
  - 月報の担当工程
- 他にも何かあれば

# 再現・確認手順（任意）
参考 #376 

# ToDo

- [x] ラベル付け

**Comment by bakunyo** [comment]
MergeされたのでClose
