### ISSUE TITLE
メールの形式を text/plain に統一する

### ISSUE THREAD

**Issue by bakunyo** [hr-dash/hr-dash#382]
# 概要
https://github.com/hr-dash/hr-dash/issues/381 に関連して。

# 再現・確認手順（任意）

# ToDo

- [x] ラベル付け

**Comment by Nobuhiko-Kudo** [comment]
動作確認OKなのでマージします！
https://lgtm.in/p/2pAt13IVp

**Comment by Nobuhiko-Kudo** [comment]
![LGTM](https://lgtm.in/p/axe5t6jaq)

**Comment by bakunyo** [comment]
MergeされたのでClose
