### ISSUE TITLE
タグ選択時のスクロールで挙動がおかしい

### ISSUE THREAD

**Issue by bakunyo** [hr-dash/hr-dash#392]
# 概要
```
月報登録フォームで「使用した技術」を登録する際に出てくるメニューのスクロールバー上で操作を行う(操作後にmouseupする)とメニューが消えます。
メニューの量が多く普通にスクロールするだけだと見づらいので、スクロールバー上での操作後も項目選択までメニューを消さないでほしいです。

【UserAgent】 Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
```

# 再現・確認手順（任意）
Win7 / Chrome で現象確認済。スクロールバーを動かすと、 `mouseup` 時にセレクトボックスが消える

![scroll](https://cloud.githubusercontent.com/assets/2487437/21534892/02c59fcc-cdb1-11e6-917e-f942c207369a.gif)

# ToDo

- [x] ラベル付け

**Comment by bakunyo** [comment]
Win10 / Chrome でも再現

**Comment by ta-chibana** [comment]
merged
