### ISSUE TITLE
Tagに新たなstatusを追加する

### ISSUE THREAD

**Issue by ta-chibana** [hr-dash/hr-dash#400]
# 概要
- 現状、 `fixed` にしないことを決めたタグを判別する方法が存在しない
- `fixed`, `unfixed` の他に`ignored`を追加する（もっと良さげな名前あればそちらでも）
- 例えば管理画面のダッシュボードで利用することを想定

# 再現・確認手順（任意）
なし

# ToDo

- [x] ラベル付け

**Comment by bakunyo** [comment]
MergeされたのでClose
