### ISSUE TITLE
対象月を検索項目に含める

### ISSUE THREAD

**Issue by bakunyo** [hr-dash/hr-dash#406]
# 概要
月報（トップ）の検索項目に対象月を含める

# 再現・確認手順（任意）

# ToDo

- [x] ラベル付け

**Comment by masahiro-yamazaki** [comment]
http://railsdoc.com/references/date_select
http://blog.inouetakuya.info/entry/2014/01/31/233000
http://qiita.com/satomyumi/items/6a64280eb41c2881fa31
http://qiita.com/t_oginogin/items/519fb52e1708e26a8b73

**Comment by bakunyo** [comment]
MergeされたのでClose
