### ISSUE TITLE
コメント入力欄の下にあるメッセージを月報作成画面に合わせる。

### ISSUE THREAD

**Issue by t-tonchim** [hr-dash/hr-dash#413]
# 概要
月報作成・編集画面では
- [Markdown](https://help.github.com/articles/basic-writing-and-formatting-syntax/)記法が使えます。

コメント入力欄では
- You can use [GFM](https://help.github.com/categories/writing-on-github/) except for HTML.

となっていて、それぞれ異なるメッセージになっているのと、リンク先も違うので月報の画面に合わせる。

# 再現・確認手順（任意）

# ToDo

- [x] ラベル付け

**Comment by bakunyo** [comment]
MergeされたのでClose
