### ISSUE TITLE
月報一覧で投稿日を表示する

### ISSUE THREAD

**Issue by bakunyo** [hr-dash/hr-dash#414]
# 概要
月報一覧で投稿日を表示する

# 再現・確認手順（任意）

# ToDo

- [x] ラベル付け

**Comment by masahiro-yamazaki** [comment]
◆確認事項◆
投稿日は”shipping_date(公開日)”という認識で問題ないでしょうか？

**Comment by bakunyo** [comment]
@masahiro-yamazaki 
`shipping_date` ではなく、 `shipped_at` ですね

**Comment by ta-chibana** [comment]
merged.
