### ISSUE TITLE
コメント更新時のボタンのメッセージを変更する。

### ISSUE THREAD

**Issue by t-tonchim** [hr-dash/hr-dash#417]
# 概要
- コメント編集した後に更新する時のボタンが `Comment` のままでちょっとややこしいので `更新` とかにする
- そもそも`Comment` だけ英語なのでついでに日本語にする
- `[ユーザー名] Commented yyyy/MM/dd` の `Commented` のとこも `[ユーザー名] さんがyyyy/MM/ddにコメント` とかにする

# 再現・確認手順（任意）

# ToDo

- [x] ラベル付け

**Comment by bakunyo** [comment]
MergeされたのでClose
