### ISSUE TITLE
HTTPS対応する

### ISSUE THREAD

**Issue by t-tonchim** [hr-dash/hr-dash#438]
# 概要
httpsに対応させる。インフラ側の対応も必要

# 再現・確認手順（任意）

# ToDo

- [x] ラベル付け
- [ ] productionで起動できるようにする。
- [ ] nginxでhttpsの設定をする。
- [ ] application_controllerでforce_sslする
- [ ] mixed contentsを潰す(cdn使ってるとこくらい？)

**Comment by bakunyo** [comment]
対応完了
