### ISSUE TITLE
月報登録失敗後に登録画面で【Update(月報を更新)】ボタンが表示されてしまう

### ISSUE THREAD

**Issue by masahiro-yamazaki** [hr-dash/hr-dash#459]
# 概要
月報登録画面で【Update(月報を更新)】ボタンが表示されてしまう

# 再現・確認手順（任意）
月報登録画面で「使用した技術」が空欄の状態で【ShippedShip(保存して公開)】ボタンを押すと、
「使用した技術を入力してください」のアラートが表示され「月報登録」画面に戻るが、
Submitボタンが【Update(月報を更新)】に変化してしまう。

# ToDo

- [ ] ラベル付け

**Comment by bakunyo** [comment]
MergeされたのでClose
