### ISSUE TITLE
gem did_you_mean　導入

### ISSUE THREAD

**Issue by t-tonchim** [hr-dash/hr-dash#80]
https://github.com/yuki24/did_you_mean
typoしたときに、もしかしてこれじゃね？って教えてくれるいいやつ

**Comment by bakunyo** [comment]
Ruby2.3から標準で入ってくるっぽいです。
クリスマス頃にリリース予定っぽいので、2.3出たらバージョンアップして対応しましょうか〜
（1ヶ月間だけ入れといてもいいですが）

```
This gem will automatically be activated when a Ruby process starts up. No special setup is required.
```

https://bugs.ruby-lang.org/issues/11252
